version: '3'

services:
  # lado do administrador
  site:
    build: .
    container_name: you-search
    volumes: 
      - .:/var/www/html
    ports:
      - 8080:8080
    networks:
      - you-search

networks:
  you-search: 
    driver: bridge